### ISSUE TITLE
GetPortfolioMargins returns error after multiple attempts (15mins apart)

### ISSUE THREAD

**Issue by Tradyn** [psollberger/DeriSock#58]
**Describe the bug**
          Unhandled exception. System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host..
           ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
             at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
             at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsyncForNetworkStream(Socket socket, CancellationToken cancellationToken)
             at System.Net.Sockets.NetworkStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
             at System.Net.Security.SslStream.WriteSingleChunk[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
             at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
             at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
             at System.Net.Security.SslStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
             at System.Net.Http.HttpConnection.WriteToStreamAsync(ReadOnlyMemory`1 source, Boolean async)
             at System.Net.Http.HttpConnection.WriteWithoutBufferingAsync(ReadOnlyMemory`1 source, Boolean async)
             at System.Net.Http.HttpConnection.RawConnectionStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
             at System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync(MessageOpcode opcode, Boolean endOfMessage, Boolean disableCompression, ReadOnlyMemory`1 payloadBuffer)
             at System.Net.WebSockets.ManagedWebSocket.SendFrameAsync(MessageOpcode opcode, Boolean endOfMessage, Boolean disableCompression, ReadOnlyMemory`1 payloadBuffer, CancellationToken cancellationToken)
             at System.Net.WebSockets.ManagedWebSocket.SendAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, WebSocketMessageFlags messageFlags, CancellationToken cancellationToken)
             at System.Net.WebSockets.ManagedWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
             at System.Net.WebSockets.ClientWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
             at DeriSock.Net.JsonRpc.DefaultJsonRpcMessageSource.Send(String message, CancellationToken cancellationToken) in G:\CryptoRepos\DeriSock\src\DeriSock\Net\JsonRpc\DefaultJsonRpcMessageSource.cs:line 105
             at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
             at DeriSock.Net.JsonRpc.DefaultJsonRpcMessageSource.Send(String message, CancellationToken cancellationToken)
             at DeriSock.DeribitClient.Send[T](String method, Object params, IJsonConverter`1 converter, CancellationToken cancellationToken) in G:\CryptoRepos\DeriSock\src\DeriSock\DeribitClient.cs:line 154
             at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
             at DeriSock.DeribitClient.Send[T](String method, Object params, IJsonConverter`1 converter, CancellationToken cancellationToken)
             at DeriSock.DeribitClient.InternalPrivateGetPortfolioMargins(PrivateGetPortfolioMarginsRequest args, CancellationToken cancellationToken) in G:\CryptoRepos\DeriSock\src\DeriSock\DeribitClient_AccountManagement.cs:line 60
             at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
             at DeriSock.DeribitClient.InternalPrivateGetPortfolioMargins(PrivateGetPortfolioMarginsRequest args, CancellationToken cancellationToken)   at DeriSock.DeribitClient.PrivateApiImpl.DeriSock.Api.IPrivateApi.GetPortfolioMargins(PrivateGetPortfolioMarginsRequest args, CancellationToken cancellationToken) in G:\CryptoRepos\DeriSock\src\DeriSock\Api\PrivateApiImpl.g.cs:line 413
             at Deribit.Core.Deribit.SimulatePositions(CurrencySymbol currency, IDictionary`2 positions, Boolean addToPositions) in G:\Crypto\crypto\Deribit.Core\Deribit.Core\Deribit.cs:line 174
             at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
             at Deribit.Core.Deribit.SimulatePositions(CurrencySymbol currency, IDictionary`2 positions, Boolean addToPositions)

**To Reproduce**

1. Is the problem happening on Testnet or Productive?
2. Which method(s) are you calling or what subscriptions did you subscribe to?
3. What are the parameters used for the method(s)/subscribtion(s)?

**Expected behavior**

**Additional context**

**Comment by Tradyn** [comment]
Could have been an exchange issue.. i will leave until you see or close.
Thanks bro.

**Comment by Tradyn** [comment]
Unhandled exception. System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsyncForNetworkStream(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.NetworkStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.WriteSingleChunk[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Security.SslStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.WriteToStreamAsync(ReadOnlyMemory`1 source, Boolean async)
   at System.Net.Http.HttpConnection.WriteWithoutBufferingAsync(ReadOnlyMemory`1 source, Boolean async)
   at System.Net.Http.HttpConnection.RawConnectionStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync(MessageOpcode opcode, Boolean endOfMessage, Boolean disableCompression, ReadOnlyMemory`1 payloadBuffer)
   at System.Net.WebSockets.ManagedWebSocket.SendFrameAsync(MessageOpcode opcode, Boolean endOfMessage, Boolean disableCompression, ReadOnlyMemory`1 payloadBuffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.SendAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, WebSocketMessageFlags messageFlags, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
   at System.Net.WebSockets.ClientWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
   at DeriSock.Net.JsonRpc.DefaultJsonRpcMessageSource.Send(String message, CancellationToken cancellationToken) in G:\CryptoRepos\DeriSock\src\DeriSock\Net\JsonRpc\DefaultJsonRpcMessageSource.cs:line 105
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at DeriSock.Net.JsonRpc.DefaultJsonRpcMessageSource.Send(String message, CancellationToken cancellationToken)
   at DeriSock.DeribitClient.Send[T](String method, Object params, IJsonConverter`1 converter, CancellationToken cancellationToken) in G:\CryptoRepos\DeriSock\src\DeriSock\DeribitClient.cs:line 154
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at DeriSock.DeribitClient.Send[T](String method, Object params, IJsonConverter`1 converter, CancellationToken cancellationToken)
   at DeriSock.DeribitClient.InternalPrivateGetPortfolioMargins(PrivateGetPortfolioMarginsRequest args, CancellationToken cancellationToken) in G:\CryptoRepos\DeriSock\src\DeriSock\DeribitClient_AccountManagement.cs:line 60
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at DeriSock.DeribitClient.InternalPrivateGetPortfolioMargins(PrivateGetPortfolioMarginsRequest args, CancellationToken cancellationToken)
   at DeriSock.DeribitClient.PrivateApiImpl.DeriSock.Api.IPrivateApi.GetPortfolioMargins(PrivateGetPortfolioMarginsRequest args, CancellationToken cancellationToken) in G:\CryptoRepos\DeriSock\src\DeriSock\Api\PrivateApiImpl.g.cs:line 413

**Comment by Tradyn** [comment]
So i keep getting this error when sending Rest requests?

**Comment by psollberger** [comment]
Heartbeats are handled internally. They are not accessible from the outside at the moment.

They can be enabled/disabled like this ...
```cs
    await client.Public.SetHeartbeat(new PublicSetHeartbeatRequest { Interval = 10 });
    await client.Public.DisableHeartbeat();
```

... but the only thing done with it in the client at the moment is ...

```cs
  private void OnHeartbeat(Heartbeat heartbeat)
  {
    _logger?.Debug("OnHeartbeat: {@Heartbeat}", heartbeat);

    if (heartbeat.Type == "test_request")
      _ = InternalPublicTest();
  }
```

Can you enable heartbeats as they are implemented right now and observe if the problem still exists?

**Comment by Tradyn** [comment]
This is driving me crazy now.. there must be an error somewhere.. nothing runs more than a minute now... any http request just throws this error...

**Comment by psollberger** [comment]
I just added an auto reconnect mechanism on socket error.

Assumedly this will not solve your underlying issue but at least reconnect the connection (and reauthenticate as well) when the connection was broken or the remote did hang-up on you.

**Comment by Tradyn** [comment]
thanks for making changes

can you change the auto gen files to include changes to the comboleg class please?
